services:
  db:
    image: postgres:16
    container_name: kopikita-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kopikita
      POSTGRES_USER: kopikita
      POSTGRES_PASSWORD: kopikita123
    ports:
      - "5432:5432"
    volumes:
      - kopikita-postgres-data:/var/lib/postgresql/data

volumes:
  kopikita-postgres-data:
